# Generated by https://kamatera.github.io/kamateratoolbox/serverconfiggen.html?configformat=terraform
terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "2.22.0"
    }
  }
}

# Docker
data "terraform_remote_state" "docker-server" {
  backend = "local"

  config = {
    path = "../kamatera-docker/terraform.tfstate"
  }
}

provider "docker" {
  host     = "ssh://root@${data.terraform_remote_state.docker-server.outputs.public_ip}"
  ssh_opts = ["-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null"]
}

# Pulls the image
resource "docker_image" "httpd-image" {
  name = "httpd:alpine"
}

# Create a container
resource "docker_container" "httpd-container" {
  image = docker_image.httpd-image.image_id
  name  = "apache"
  ports {
    internal = 80
    external = 80
  }
}
